spring.application.name=Dairy

spring.datasource.url=jdbc:mysql://localhost:3306/dairy?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= Mysql,009
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
